export const CANVAS = {
    SIZE: 600,
    MIDDLE: 300,
    PADDING: 10,
    RADIUS: 16,
    GAP: 26
};

export const HORIZONTAL_PATH_LIST = [
    [CANVAS.GAP, CANVAS.GAP, CANVAS.MIDDLE - CANVAS.GAP],
    [CANVAS.GAP, CANVAS.MIDDLE + CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP],
    [CANVAS.GAP + CANVAS.RADIUS * 5, CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP],
    [CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 6]
];

export const VERTICAL_PATH_LIST = [
    [CANVAS.GAP, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 9],
    [CANVAS.MIDDLE - CANVAS.GAP, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 5],
    [CANVAS.GAP + CANVAS.RADIUS * 6, CANVAS.GAP, CANVAS.SIZE - CANVAS.RADIUS * 6]
];

export const WALLS = [
    [0, 0, CANVAS.SIZE, CANVAS.PADDING],
    [0, 0, CANVAS.PADDING, CANVAS.SIZE],
    [CANVAS.SIZE - CANVAS.PADDING, 0, CANVAS.PADDING, CANVAS.SIZE],
    [0, CANVAS.SIZE - CANVAS.PADDING, CANVAS.SIZE, CANVAS.PADDING],
    [CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.RADIUS * 4, CANVAS.RADIUS * 3],
    [CANVAS.PADDING + CANVAS.RADIUS * 8, CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.RADIUS * 7.5, CANVAS.RADIUS * 3]
];
