export const CANVAS = {
    SIZE: 600,
    MIDDLE: 300,
    PADDING: 10,
    RADIUS: 16,
    GAP: 26
};

export const HORIZONTAL_PATH_LIST = [
    // TOP 1: TWO
    [CANVAS.GAP, CANVAS.GAP, CANVAS.MIDDLE - CANVAS.RADIUS * 2],
    [CANVAS.GAP, CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.SIZE - CANVAS.GAP],

    // TOP 2: ONE
    [CANVAS.GAP + CANVAS.RADIUS * 5, CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP],

    // TOP 3: FOUR
    [CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 6],
    [CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.MIDDLE - CANVAS.RADIUS * 2],
    [CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.MIDDLE + CANVAS.RADIUS * 8],
    [CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.MIDDLE + CANVAS.RADIUS * 12, CANVAS.SIZE - CANVAS.GAP],

    // MIDDLE 1: ONE
    [CANVAS.GAP + CANVAS.RADIUS * 13, CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.MIDDLE + CANVAS.RADIUS * 8],

    // MIDDLE 2: THREE
    [CANVAS.MIDDLE - CANVAS.GAP, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 10],
    [CANVAS.MIDDLE - CANVAS.GAP, CANVAS.MIDDLE - CANVAS.RADIUS * 2, CANVAS.MIDDLE + CANVAS.PADDING + CANVAS.RADIUS * 2],
    [CANVAS.MIDDLE - CANVAS.GAP, CANVAS.MIDDLE + CANVAS.RADIUS * 8, CANVAS.SIZE - CANVAS.GAP],

    // MIDDLE 3: ONE
    [CANVAS.GAP + CANVAS.RADIUS * 18, CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.MIDDLE + CANVAS.RADIUS * 8],

    // BOTTOM 1: TWO
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 12, CANVAS.GAP, CANVAS.MIDDLE - CANVAS.RADIUS * 2],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 12, CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.SIZE - CANVAS.GAP],

    // BOTTOM 2: THREE
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 8, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 2],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 8, CANVAS.GAP + CANVAS.RADIUS * 6, CANVAS.SIZE - CANVAS.RADIUS * 8],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 8, CANVAS.MIDDLE + CANVAS.RADIUS * 15, CANVAS.SIZE - CANVAS.GAP],

    // BOTTOM 3: FOUR
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 6],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4, CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.MIDDLE - CANVAS.RADIUS * 2],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4, CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.MIDDLE + CANVAS.RADIUS * 8],
    [CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4, CANVAS.MIDDLE + CANVAS.RADIUS * 12, CANVAS.SIZE - CANVAS.GAP],

    // BOTTOM 4: ONE
    [CANVAS.SIZE - CANVAS.GAP, CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP]
];

export const VERTICAL_PATH_LIST = [
    // LEFT 1: THREE
    [CANVAS.GAP, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 9],

    // LEFT 2: ONE
    [CANVAS.GAP + CANVAS.RADIUS * 6, CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4],

    // TOP MIDDLE: FOUR
    [CANVAS.MIDDLE - CANVAS.RADIUS * 2, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 5],
    [CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 5],
    [CANVAS.MIDDLE - CANVAS.RADIUS * 2, CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.GAP + CANVAS.RADIUS * 13],
    [CANVAS.MIDDLE + CANVAS.RADIUS * 2, CANVAS.GAP + CANVAS.RADIUS * 9, CANVAS.GAP + CANVAS.RADIUS * 13],

    // LEFT 3: THREE
    [CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.GAP + CANVAS.RADIUS * 5, CANVAS.GAP + CANVAS.RADIUS * 9],
    [CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.GAP + CANVAS.RADIUS * 13, CANVAS.GAP + CANVAS.RADIUS * 18],
    [CANVAS.GAP + CANVAS.RADIUS * 10, CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 8, CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4],

    // RIGHT 1; THREE
    [CANVAS.MIDDLE + CANVAS.RADIUS * 8, CANVAS.GAP + CANVAS.RADIUS * 5, CANVAS.GAP + CANVAS.RADIUS * 9],


    // RIGHT 1: ONE
    [CANVAS.MIDDLE + CANVAS.RADIUS * 12, CANVAS.GAP, CANVAS.SIZE - CANVAS.GAP - CANVAS.RADIUS * 4],

    // RIGHT 3: THREE
    [CANVAS.SIZE - CANVAS.GAP, CANVAS.GAP, CANVAS.GAP + CANVAS.RADIUS * 9]
];

export const WALLS = [
    [0, 0, CANVAS.SIZE, CANVAS.PADDING],
    [0, 0, CANVAS.PADDING, CANVAS.SIZE],
    [CANVAS.SIZE - CANVAS.PADDING, 0, CANVAS.PADDING, CANVAS.SIZE],
    [0, CANVAS.SIZE - CANVAS.PADDING, CANVAS.SIZE, CANVAS.PADDING],

    [CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.RADIUS * 4, CANVAS.RADIUS * 3],
    [CANVAS.PADDING + CANVAS.RADIUS * 8, CANVAS.PADDING + CANVAS.RADIUS * 2, CANVAS.RADIUS * 7, CANVAS.RADIUS * 3]
];
